### PR TITLE
Add/fix some tests, plus some cleanup and formatting

### PR DESCRIPTION
**Pull request by zengjian-hu-rai**
Add two simple tests per suggestion from @chriscoey

### CODE REVIEW

**Review by chriscoey — APPROVED** [review]
Looks good, thanks Jian!

**Comment by zengjian-hu-rai** [comment]
> Looks good, thanks Jian!

thanks, but not sure why two tests are failing. attempted to fix with issetequal() but still not working. all tests are passing on my local.

Test Summary:                      | Pass  Total  Time
SolverAPI                          |   43     43  0.9s
  test                             |   43     43      
    test/solve_tests.jl            |   43     43      
      solve                        |    7      7  0.5s
        feas_range                 |    1      1  0.1s
        min_range                  |    1      1  0.0s
        tiny_min                   |    1      1  0.0s
        tiny_feas                  |    1      1  0.1s
        tiny_infeas                |    1      1  0.1s
        simple_lp                  |    1      1  0.0s
        n_queens                   |    1      1  0.1s
      print                        |    6      6  0.0s
      validate                     |   30     30  0.0s
        feas_with_obj              |    2      2  0.0s
        min_no_obj                 |    2      2  0.0s
        unsupported_sense          |    2      2  0.0s
        obj_len_greater_than_1     |    2      2  0.0s
        incorrect_range_num_params |    2      2  0.0s
        incorrect_range_step_not_1 |    2      2  0.0s
        vars_is_not_str            |    2      2  0.0s
        vars_is_not_arr            |    2      2  0.0s
        objs_is_not_arr            |    2      2  0.0s
        cons_is_not_arr            |    2      2  0.0s
        missing_vars               |    2      2  0.0s
        missing_cons               |    2      2  0.0s
        missing_objs               |    2      2  0.0s
        missing_sense              |    2      2  0.0s
        missing_version            |    2      2  0.0s

**Comment by chriscoey** [comment]
This is done, but marking as draft so we don't merge before https://relationalai.atlassian.net/browse/RAI-16251 is fixed.

after this, to run JuliaFormatter, you just do `format(".")` (it uses the new JuliaFormatter.toml to keep things consistent). we could add a CI run to check the format before merging, like we do over at CSP2SAT.jl

**Comment by chriscoey** [comment]
Sorry to squeeze in multiple changes in one PR - got a little carried away 😄

**Pull request merged**
